<?php return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'open sans' => array(
    '300_italic' => $fontDir . '/open-sans-300-italic_411872681a317b0ccb406742d515a314',
    'italic' => $fontDir . '/open-sans-italic_27fb03d2bf8c49880fbd15f3f96b7504',
    '600_italic' => $fontDir . '/open-sans-600-italic_d1b486ea88688c1629a580f4d3892e32',
    'bold_italic' => $fontDir . '/open-sans-bold-italic_68f518df61d7a8314654ce172af86e08',
    '800_italic' => $fontDir . '/open-sans-800-italic_1111cda53b4d3e6dde5a20c26ddcdaa2',
    '300' => $fontDir . '/open-sans-300_771fb82d4990c29fe5ca012c48dba770',
    'normal' => $fontDir . '/open-sans-normal_e506610fef0257e1844aa011b3f4e88e',
    '600' => $fontDir . '/open-sans-600_132792df4309018ac172d56fb73c5a4c',
    'bold' => $fontDir . '/open-sans-bold_0c5c5192428430e4a427c26cf26101cc',
    '800' => $fontDir . '/open-sans-800_9b31cb72fa555985c61d89917ed8cb08',
  ),
  'lato' => array(
    '100' => $fontDir . '/lato-100_c2b5e1963f8e58c31432507bb818a02d',
    'normal' => $fontDir . '/lato-normal_29d5b677c886f2174ede1236ece8bf48',
    'bold' => $fontDir . '/lato-bold_2fb4b282424ccdfa53348e43eebdb551',
  ),
  'material icons' => array(
    'normal' => $fontDir . '/material-icons-normal_a83785ccbfc5713b63b97bbf71e6fa23',
  ),
  'roboto' => array(
    'normal' => $fontDir . '/roboto-normal_cf99a9d56c411ce3fa8a2fc49c520e74',
    '500' => $fontDir . '/roboto-500_3fd317e52bc3050f32e57a7e30e4f32c',
    'bold' => $fontDir . '/roboto-bold_1e996688829091a02d8ce32f4ce56696',
  ),
  'calibri' => array(
    'normal' => $fontDir . '/calibri-normal_10ce7c2b160045ee1a75c85d89198f40',
    'bold' => $fontDir . '/calibri-bold_9b126f33199ab54cf94e67158294cbab',
  ),
) ?>